# https://github.com/VeryGoodOpenSource/very_good_analysis/blob/main/lib/analysis_options.5.1.0.yaml

include: package:very_good_analysis/analysis_options.5.1.0.yaml
linter:
  rules:
    always_declare_return_types: true
    avoid_print: true
    prefer_single_quotes: true
    public_member_api_docs: false
    prefer_relative_imports: true
    always_use_package_imports: false
    omit_local_variable_types: false
    lines_longer_than_80_chars: false
