name: flutter_starter_kit
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  auto_route: ^8.1.3
  connectivity_plus: ^6.0.3
  dio: ^5.4.3+1
  encrypt: ^5.0.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  flutter_localization: ^0.2.0
  get_it: ^7.7.0
  shared_preferences: ^2.2.3

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  husky: ^0.1.7
  lint_staged: ^0.5.1
  very_good_analysis: ^5.1.0

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - .env

lint_staged:
  "lib/**.dart": dart format -l 120 && dart analyze --fatal-infos --fatal-warnings

# to run command - rps setup_dev_env
scripts:
  setup_dev_env: cp .env.dev .env
  setup_prod_env: cp .env.prod .env
  setup_test_env: cp .env.test .env
  nav_generator: dart run build_runner build --delete-conflicting-outputs
  gen_locale: flutter gen-l10n
